# Generated by Django 6.1.1 on 2026-10-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_sale_delivery_charge_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(default='#198754', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
