# Generated by Django 6.1.1 on 2026-10-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_product_image_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pos.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_deals', to='pos.product')),
            ],
        ),
    ]
